name: Java CI with Maven

env:
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
  BOT_USERNAME: ${{ secrets.BOT_USERNAME }}
  SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: SERVICE_ACCOUNT

      - name: deploy
        uses: google-github-actions/deploy-appengine@v1